# Task... prep the new config directories as git repos

- name: prep_configs - GIT INIT the base configs directory as a repo
  command: git init && git config user.name "{{ source_control_username }}" && git config user.email "{{ source_control_email }}"
  args:
    chdir: /tmp/splunkPS_base_configs
- name: prep_configs - GIT add all and commit the base configs repo with date and add the remote origin
  command: git add --all && git commit -m "Update Check {{ ansible_date_time.date }}" && git remote add origin {{ source_control_url }}/splunkPS_base_configs.git
  args:
    chdir: /tmp/splunkPS_base_configs

- name: prep_configs - GIT INIT the cluster configs directory as a repo
  command: git init && git config user.name "{{ source_control_username }}" && git config user.email "{{ source_control_email }}"
  args:
    chdir: /tmp/splunkPS_cluster_configs
- name: prep_configs - GIT add all and commit the cluster configs repo with date and add the remote origin
  command: git add --all && git commit -m "Update Check {{ ansible_date_time.date }}" && git remote add origin {{ source_control_url }}/splunkPS_base_configs.git
  args:
    chdir: /tmp/splunkPS_cluster_configs